name: CI-CD

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: koteikin/argo-cd-workshop-kpi

jobs:

  build_and_push:
    runs-on: ubuntu-latest
    name: Build and push docker image
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - id: commit_hash
        run: echo "::set-output name=commit_hash::${GITHUB_SHA::7}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ steps.commit_hash.outputs.commit_hash }}

  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    needs: build_and_push
    env:
      TAG_FILE_PATH: ./deploy/myapp/values.yaml
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Update commit hash
        run: |
          sed -i -E "s/([ \t]*tag\: )(.*)/\1\'${{needs.build_and_push.outputs.commit_hash}}\'/" ${{ env.TAG_FILE_PATH }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          author_name: GitHub Actions
          committer_email: actions@github.com
          message: "update images tag to '${{needs.build_and_push.outputs.commit_hash}}'"
